FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src

COPY ["BuildingBlocks/.", "BuildingBlocks/."]
COPY ["Configurator/.", "Configurator/."]
COPY ["Configurator/Configurator.API/", "Configurator/Configurator.API/"]
COPY ["Configurator/Configurator.Application/", "Configurator/Configurator.Application/"]
COPY ["Configurator/Configurator.Infrastructure/", "Configurator/Configurator.Infrastructure/"]
COPY ["Configurator/Configurator.Domain/", "Configurator/Configurator.Domain/"]

RUN dotnet restore "Configurator/Configurator.API/Configurator.API.csproj"

RUN dotnet build "Configurator/Configurator.API/Configurator.API.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Configurator/Configurator.API/Configurator.API.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Configurator.API.dll"]

