FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /source

COPY ["BuildingBlocks/.", "BuildingBlocks/."]
COPY ["Ordering/.", "Ordering/."]
COPY ["Ordering/Ordering.API/", "Ordering/Ordering.API/"]

RUN dotnet restore "Ordering/Ordering.API/Ordering.API.csproj"

RUN dotnet build "Ordering/Ordering.API/Ordering.API.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Ordering/Ordering.API/Ordering.API.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Ordering.API.dll"]

