version: '3.9'

services:
  sqldata:
    container_name: "sqlserver"
    hostname: "sqlserver"
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - /var/mssql-data:/var/opt/mssql
  
  # nosqldata:
  #   image: mongo
  
  # rabbitmq:
  #   image: rabbitmq:3-management-alpine
  
  vehicle-inventory-api:
    build:
      context: .
      dockerfile: Dockerfile-vehicle-inventory-api
    depends_on:
      - sqldata
    ports:
      - 2500:5000




  