FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["VehicleInventory.API/VehicleInventory.API.csproj", "VehicleInventory.API/"]
COPY ["VehicleInventory.Application/VehicleInventory.Application.csproj", "VehicleInventory.Application/"]
COPY ["VehicleInventory.Infrastructure/VehicleInventory.Infrastructure.csproj", "VehicleInventory.Infrastructure/"]
COPY ["VehicleInventory.Domain/VehicleInventory.Domain.csproj", "VehicleInventory.Domain/"]

RUN dotnet restore "VehicleInventory.API/VehicleInventory.API.csproj"
COPY . .
WORKDIR "/src/VehicleInventory.API"
RUN dotnet build "VehicleInventory.API.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "VehicleInventory.API.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "VehicleInventory.API.dll"]
