apiVersion: v1
kind: Service
metadata:
  name: vehicle-inventory-api
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: vehicle-inventory-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vehicle-inventory-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vehicle-inventory-api
  template:
    metadata:
      labels:
        app: vehicle-inventory-api
    spec:
      containers:
        - name: vehicle-inventory-api
          image: makigjuro/car-config-vehicle-inv-api:latest
          resources:
            requests:
              memory: "256Mi"
              cpu: "300m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 5000
          # env:
          #   - name: NODE_ENV
          #     value: "production"
          #   - name: PORT
          #     value: "$PORT"
          #   - name: DB_NAME
          #     value: "$DB_NAME"
          #   - name: DB_USERNAME
          #     value: "$DB_USERNAME"
          #   - name: DB_PASSWORD
          #     value: "$DB_PASSWORD"
          #   - name: DB_HOST
          #     value: "$DB_HOST"
          #   - name: DB_PORT
          #     value: "$DB_PORT"
