apiVersion: apps/v1
kind: Deployment
metadata:
  name: vehicle-inv-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vehicle-inv-api
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: vehicle-inv-api
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: vehicle-inv-api
        image: makigjuro/car-config-vehicle-inv-api:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        # env:
        # - name: REDIS
        #   value: "azure-vote-back"
---
apiVersion: v1
kind: Service
metadata:
  name: vehicle-inv-api
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: vehicle-inv-api
