name: Configurator API Test & Build

on:
  push:
    branches: [ main ]
    # paths: 
    #    - 'src/services/Ordering/**'
    #    - 'src/services/BuildingBlocks/**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET for API
      uses: actions/setup-dotnet@v2
    - run: dotnet build src/services/Configurator/Configurator.API/Configurator.API.csproj
    # - run: dotnet test src/services/Configurator/Configurator.Tests/Configurator.Tests.csproj
 
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          context: src/services/
          tags: makigjuro/car-config-api:latest
          file: src/services/Dockerfile-configurator-api
