name: Deploy Vehicle Inventory API

on:
  workflow_run:
    workflows: ["Vehicle Inventory API Test & Build"]
    types:
      - completed

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:          
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.SERVICE_PRINCIPAL }}
          tenant-id: ${{ secrets.TENANT }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set AKS context
        id: set-context
        uses: azure/aks-set-context@v3
        with:
          resource-group: '${{ secrets.resource_group }}' 
          cluster-name: '${{ secrets.cluster_name }}'
      - name: Setup kubectl
        id: install-kubectl
        uses: azure/setup-kubectl@v3
      - name: Deploy to AKS
        id: deploy-aks
        uses: Azure/k8s-deploy@v4
        with:
          namespace: 'default'
          manifests: |
             vehicle-inv-deployment.yaml
          images: makigjuro/car-config-vehicle-inv-api:latest

